### ISSUE TITLE
Instructions in README don't seem to match expected paths

### ISSUE THREAD

**Issue by RussellHaley** [Tieske/luawinmake#15]
Hi, 

I'm trying to test if this script is useful with the 2017 C++ Build Tools from MS. The readme indicates that the etc folder should be copied into the lua root folder. Admittedly, I used the Lua git repository - which was a mistake because it doesn't have an src directory - but the file seemed to expect that the path to the header file was ./src/lua.h 
So from what I can tell the expected structure is:
...\etc\winmake.bat
...\etc\src\...

where as the instructed path is:
...\etc\winmake.bat
...\src\...

Perhaps the script needs another . in the path or did I miss something?

ALSO, Lua 5.4 (from the git repo) didn't build. The batch ran but didn't generate any obj files and the linker failed. Not sure if that's my fault or a consequence of the above.

Update: I had to add a . to SET SOURCETREE
```SET SOURCETREE=..\```
and then 5.3 builds fine.

**Comment by Tieske** [comment]
the problem is that you use the github repo which does not have the structure of the distribution packages.

That said, it might not be too hard to make the script more resilient to where it is located:

- `.\etc\winmake`: current required location
- `.\winmake`: alternatively in the top level directory of the repo

and also locate the sources properly relatively from `winmake` itself as either

- `..\src`: next to `etc`, current required location
- `.\`: sources in toplevel, as well as `winmake` on toplevel (your situation)
- `.\src`: sources as per distro package, but `winmake` at top level

**Comment by RussellHaley** [comment]
I was having the same issue with 5.3.  I see what I did wrong now: I stumbled in reading the build instructions. I would cd into the ```etc```  and call ```winmake.bat```. Your instructions indicate running ```etc\winmake.bat```.

Would you be interested in adding a /SOURCE_TREE option?

**Comment by Tieske** [comment]
I think I'd prefer the autodetection instead of extra options

**Comment by RussellHaley** [comment]
Understood. Perhaps even just augmenting the README instructions with a code block showing the commands would be enough to keep fools like me from mucking it.

**Comment by Tieske** [comment]
@RussellHaley can you give this branch a try: https://github.com/Tieske/luawinmake/pull/16
